// Six export targets, and the byte count next to each one.
//
// The byte count is not decoration. A design system you cannot ship is not a
// design system, and "how much does this cost me" is the question every one of
// these tools refuses to answer. Every export here is static text: no runtime,
// no dependency, nothing to install.

import { audit } from './system.mjs';

export const TARGETS = ['css', 'tailwind', 'json', 'react', 'svelte', 'html'];

const bytes = (s) => new TextEncoder().encode(s).length;
const kb = (n) => (n < 1024 ? `${n} B` : `${(n / 1024).toFixed(1)} kB`);

const varName = (k) => k.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();

// --- CSS custom properties --------------------------------------------------

export function toCss(sys) {
  const c = sys.colour;
  const t = sys.type;

  const lines = [
    `/* ${sys.vibeLabel} · seed ${sys.seed}${sys.dark ? ' · dark' : ''}`,
    ` * Generated by notugly. Every text pairing below clears WCAG AA.`,
    ` */`,
    `:root {`,
    `  /* colour */`,
    ...['bg', 'surface', 'surfaceAlt', 'text', 'textMuted', 'brand', 'accent', 'buttonBg', 'buttonText', 'border', 'focus'].map(
      (k) => `  --${varName(k)}: ${c[k]};`
    ),
    ``,
    `  /* ramps */`,
    ...c.primary.map((hex, i) => `  --primary-${i * 100 || 50}: ${hex};`),
    ...c.neutral.map((hex, i) => `  --neutral-${i * 100 || 50}: ${hex};`),
    ``,
    `  /* type */`,
    `  --font-heading: ${t.heading};`,
    `  --font-body: ${t.body};`,
    `  --font-mono: ${t.mono};`,
    ...t.scale.map((s) => `  --text-${s.name}: ${s.rem}rem;`),
    ...t.scale.map((s) => `  --leading-${s.name}: ${s.lineHeight};`),
    ...t.scale.map((s) => `  --tracking-${s.name}: ${s.letterSpacing}em;`),
    ``,
    `  /* space */`,
    ...Object.entries(sys.space).map(([k, v]) => `  --space-${k}: ${v};`),
    ``,
    `  /* radius */`,
    ...Object.entries(sys.radius).map(([k, v]) => `  --radius-${k}: ${typeof v === 'number' ? `${v}px` : v};`),
    ``,
    `  /* elevation */`,
    `  --shadow: ${sys.shadow.layers.join(', ')};`,
    `}`,
    ``,
    `/* motion — off by default for anyone who asked for that */`,
    sys.motion.css,
  ];

  return lines.join('\n');
}

// --- Tailwind ---------------------------------------------------------------

export function toTailwind(sys) {
  const c = sys.colour;
  const ramp = (arr, prefix) =>
    Object.fromEntries(arr.map((hex, i) => [String(i * 100 || 50), hex]));

  const config = {
    theme: {
      extend: {
        colors: {
          bg: c.bg,
          surface: c.surface,
          'surface-alt': c.surfaceAlt,
          ink: c.text,
          muted: c.textMuted,
          brand: ramp(c.primary),
          accent: ramp(c.accentRamp),
          neutral: ramp(c.neutral),
          border: c.border,
          focus: c.focus,
        },
        fontFamily: {
          heading: sys.type.heading.split(',').map((s) => s.trim().replace(/^"|"$/g, '')),
          body: sys.type.body.split(',').map((s) => s.trim().replace(/^"|"$/g, '')),
          mono: sys.type.mono.split(',').map((s) => s.trim().replace(/^"|"$/g, '')),
        },
        fontSize: Object.fromEntries(
          sys.type.scale.map((s) => [s.name, [`${s.rem}rem`, { lineHeight: String(s.lineHeight), letterSpacing: `${s.letterSpacing}em` }]])
        ),
        borderRadius: Object.fromEntries(Object.entries(sys.radius).map(([k, v]) => [k, `${v}px`])),
        boxShadow: { DEFAULT: sys.shadow.layers.join(', ') },
      },
    },
  };

  return `// ${sys.vibeLabel} · seed ${sys.seed}\n/** @type {import('tailwindcss').Config} */\nexport default ${JSON.stringify(config, null, 2)};\n`;
}

// --- design tokens (Style Dictionary / Figma shaped) ------------------------

export function toJson(sys) {
  const c = sys.colour;
  const tok = (value, type) => ({ $value: value, $type: type });

  return JSON.stringify(
    {
      $description: `notugly · ${sys.vibeLabel} · seed ${sys.seed}`,
      color: {
        bg: tok(c.bg, 'color'),
        surface: tok(c.surface, 'color'),
        text: tok(c.text, 'color'),
        muted: tok(c.textMuted, 'color'),
        brand: tok(c.brand, 'color'),
        accent: tok(c.accent, 'color'),
        border: tok(c.border, 'color'),
        focus: tok(c.focus, 'color'),
        primary: Object.fromEntries(c.primary.map((h, i) => [String(i * 100 || 50), tok(h, 'color')])),
        neutral: Object.fromEntries(c.neutral.map((h, i) => [String(i * 100 || 50), tok(h, 'color')])),
      },
      fontFamily: {
        heading: tok(sys.type.heading, 'fontFamily'),
        body: tok(sys.type.body, 'fontFamily'),
        mono: tok(sys.type.mono, 'fontFamily'),
      },
      fontSize: Object.fromEntries(sys.type.scale.map((s) => [s.name, tok(`${s.rem}rem`, 'dimension')])),
      spacing: Object.fromEntries(Object.entries(sys.space).map(([k, v]) => [k, tok(v, 'dimension')])),
      borderRadius: Object.fromEntries(Object.entries(sys.radius).map(([k, v]) => [k, tok(`${v}px`, 'dimension')])),
      shadow: tok(sys.shadow.layers.join(', '), 'shadow'),
    },
    null,
    2
  );
}

// --- components -------------------------------------------------------------

const componentBody = (sys) => {
  const c = sys.colour;
  return {
    button: `padding: var(--space-3) var(--space-6);
  border-radius: var(--radius-md);
  background: ${c.buttonBg};
  color: ${c.buttonText};
  border: ${sys.borderWeight}px solid ${sys.borderWeight ? c.border : 'transparent'};
  font-family: var(--font-body);
  font-weight: 600;
  cursor: pointer;`,
    card: `padding: var(--space-6);
  border-radius: var(--radius-lg);
  background: ${sys.glass ? `color-mix(in srgb, ${c.surface} 70%, transparent)` : c.surface};
  ${sys.glass ? 'backdrop-filter: blur(14px);\n  ' : ''}border: ${Math.max(1, sys.borderWeight)}px solid ${c.border};
  box-shadow: ${sys.shadow.layers.join(', ')};`,
  };
};

export function toReact(sys) {
  const b = componentBody(sys);
  return `// ${sys.vibeLabel} · seed ${sys.seed}
// Plain React. No styled-components, no CSS-in-JS runtime, no dependency.
import './notugly.css';

export const Button = ({ children, ...props }) => (
  <button style={{ ${cssToStyleObject(b.button)} }} {...props}>{children}</button>
);

export const Card = ({ children, ...props }) => (
  <div style={{ ${cssToStyleObject(b.card)} }} {...props}>{children}</div>
);
`;
}

export function toSvelte(sys) {
  const b = componentBody(sys);
  return `<!-- ${sys.vibeLabel} · seed ${sys.seed} -->
<script>
  export let variant = 'button';
</script>

{#if variant === 'card'}
  <div class="card"><slot /></div>
{:else}
  <button class="button"><slot /></button>
{/if}

<style>
  .button {
  ${b.button}
  }
  .card {
  ${b.card}
  }
</style>
`;
}

export function toHtml(sys) {
  const c = sys.colour;
  return `<!doctype html>
<html lang="en" ${sys.dark ? 'data-theme="dark"' : ''}>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${sys.vibeLabel} — notugly seed ${sys.seed}</title>
<style>
${toCss(sys)}

body {
  margin: 0;
  background: var(--bg);
  color: var(--text);
  font-family: var(--font-body);
  font-size: var(--text-base);
  line-height: var(--leading-base);
}
h1, h2, h3 { font-family: var(--font-heading); letter-spacing: var(--tracking-3xl); }
.wrap { max-width: 60ch; margin: 0 auto; padding: var(--space-12) var(--space-6); }
.card {
  ${componentBody(sys).card}
}
.button {
  ${componentBody(sys).button}
}
</style>
</head>
<body>
  <main class="wrap">
    <h1>${sys.vibeLabel}</h1>
    <p>Seed <code>${sys.seed}</code>. Every pairing on this page clears WCAG AA.</p>
    <div class="card">
      <h3>A card</h3>
      <p style="color: var(--text-muted)">Muted text, still readable — that is the whole point.</p>
      <button class="button">A button</button>
    </div>
  </main>
</body>
</html>
`;
}

// React's style prop wants camelCase keys, so the CSS has to be reshaped.
function cssToStyleObject(css) {
  return css
    .split(';')
    .map((d) => d.trim())
    .filter(Boolean)
    .map((d) => {
      const i = d.indexOf(':');
      const prop = d.slice(0, i).trim().replace(/-([a-z])/g, (_, ch) => ch.toUpperCase());
      const val = d.slice(i + 1).trim();
      return `${prop}: '${val.replace(/'/g, "\\'")}'`;
    })
    .join(', ');
}

// --- the thing callers actually use -----------------------------------------

export function exportAll(sys) {
  const files = {
    'notugly.css': toCss(sys),
    'tailwind.config.js': toTailwind(sys),
    'tokens.json': toJson(sys),
    'notugly.jsx': toReact(sys),
    'Notugly.svelte': toSvelte(sys),
    'index.html': toHtml(sys),
  };

  const a = audit(sys);
  return {
    files,
    sizes: Object.fromEntries(Object.entries(files).map(([k, v]) => [k, { bytes: bytes(v), human: kb(bytes(v)) }])),
    // The claim, attached to the artefact rather than to the marketing.
    accessible: a.passed,
    weakestRatio: a.weakest.ratio,
    runtimeBytes: 0,
  };
}

export { bytes, kb };
