// Vibes: five complete opinions, so you can start from a look rather than a
// blank slider.
//
// Each one fixes the decisions that have to agree with each other — radius,
// shadow depth, chroma, type pairing, motion — because those are exactly the
// choices that make a design feel coherent or feel assembled by committee.

export const VIBES = {
  editorial: {
    label: 'Editorial',
    blurb: 'Serif headlines, generous measure, almost no shadow. Reads like something printed.',
    radius: 2,
    shadow: 'flat',
    chroma: 0.72,
    ratio: 1.333,
    pairing: 'Editorial',
    motion: 'fade-in',
    pattern: 'grain',
    surfaceTint: 0.02,
    borderWeight: 1,
  },
  brutalist: {
    label: 'Brutalist',
    blurb: 'Hard edges, thick borders, no shadow, colour used like a warning sign.',
    radius: 0,
    shadow: 'flat',
    chroma: 1.35,
    ratio: 1.5,
    pairing: 'Impact',
    motion: 'pop',
    pattern: 'grid',
    surfaceTint: 0,
    borderWeight: 3,
  },
  glassy: {
    label: 'Glassy',
    blurb: 'Soft, translucent, heavily blurred. The look everyone shipped in 2021 and still wants.',
    radius: 20,
    shadow: 'floating',
    chroma: 0.9,
    ratio: 1.25,
    pairing: 'Swiss',
    motion: 'blur-in',
    pattern: 'grain',
    surfaceTint: 0.06,
    borderWeight: 1,
    glass: true,
  },
  terminal: {
    label: 'Terminal',
    blurb: 'Monospace everything, tight grid, one accent colour doing all the work.',
    radius: 4,
    shadow: 'low',
    chroma: 1.1,
    ratio: 1.2,
    pairing: 'Terminal',
    motion: 'fade-in',
    pattern: 'lines',
    surfaceTint: 0.01,
    borderWeight: 1,
  },
  playful: {
    label: 'Playful',
    blurb: 'Big radii, bouncy motion, saturated colour. Cheerful without being a toy.',
    radius: 28,
    shadow: 'medium',
    chroma: 1.25,
    ratio: 1.25,
    pairing: 'Warm',
    motion: 'scale-in',
    pattern: 'dots',
    surfaceTint: 0.04,
    borderWeight: 0,
  },
  liquidglass: {
    label: 'Liquid Glass',
    blurb: "Apple's 2025 material: translucent, specular, concentric corners — and only as readable as whatever happens to be behind it, which is exactly what gets checked here.",
    radius: 22,
    shadow: 'floating',
    chroma: 0.85,
    ratio: 1.25,
    pairing: 'Swiss',
    motion: 'blur-in',
    pattern: 'grain',
    surfaceTint: 0.05,
    borderWeight: 1,
    glass: true,
    liquidGlass: true,
  },
};

export const VIBE_NAMES = Object.keys(VIBES);
export const vibe = (name) => VIBES[name] || VIBES.editorial;
